### ISSUE TITLE
v0.2 checklist

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/jsonify#35]
TODO

- [ ] geojsonsf e692169 builds, compiles & tests
- [ ] spatialwidget 8e13f94 builds, compiles & tests
- [ ] mapdeck 1dfb182 builds, compiles & tests
